name: homework_tracker
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  uuid: ^4.5.1
  shared_preferences: ^2.2.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
